# By nikitSwaraj
---
- hosts: webservers
  sudo: yes
  remote_user: root
  tasks: 
      - name: Updating System
        yum: name=* state=latest
      - name: Opening port for http
        firewalld: port=80/tcp permanent=yes state=enabled
        notify: restart firewalld
      - name: Closing port for mail server
        firewalld: port=25/tcp permanent=yes state=enabled
        notify: restart firewalld

